name: release
on:
  create:
    tags:
      - "*.*"
      - "*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create archive
      run: make archive
    - name: upload
      env:
        PACKAGE_NAME: "headless-theme"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOPATH: /home/runner/go
      run: |
        # retrieve tag and replase version number in file.
        export CREATE_EVENT_REF_TYPE=$(jq --raw-output .ref_type "$GITHUB_EVENT_PATH")
        export TAGNAME=$(jq --raw-output .ref "$GITHUB_EVENT_PATH")
        # install ghr, then upload archve.
        go get -u github.com/tcnksm/ghr
        ${GOPATH}/bin/ghr -b "${PACKAGE_NAME} ${TAGNAME}" -replace ${TAGNAME} ${PACKAGE_NAME}.zip
