name: syntax
on:
  push:
    paths:
    - '**.php'

jobs:
  syntax:
    name: SyntaxCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Smiple syntax checker
        run: php -l *.php
